apiVersion: v1
kind: Pod
metadata:
  name: actual-pod
  labels:
    app: actual
    io.containers.autoupdate: "image"
spec:
  restartPolicy: Always
  automountServiceAccountToken: false
  containers:
  - name: actual-server
    image: docker.io/actualbudget/actual-server:latest
    ports:
    - containerPort: 5006
      name: http-actual
    env:
    # Opzionali: vedi docs per limiti upload e porta
    - name: ACTUAL_PORT
      value: "5006"
    # - name: ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB
    #   value: "20"
    volumeMounts:
    - name: actual-data
      mountPath: /data
    resources:
      requests:
        cpu: "50m"
        memory: 128Mi
      limits:
        memory: 256Mi
  volumes:
  - name: actual-data
    hostPath:
      path: /home/osvaldo/podman/data/actual   # <- metti qui il tuo mount sullo storage box
      type: DirectoryOrCreate
