apiVersion: v1
kind: Pod
metadata:
  name: firefly-importer-pod
  labels:
    app: firefly-importer
spec:
  automountServiceAccountToken: false
  
  # Init container - solo crea struttura
  initContainers:
  - name: init-storage
    image: docker.io/fireflyiii/data-importer:latest
    securityContext:
      runAsUser: 33  # <-- Esegui come www-data
      runAsGroup: 33
    command:
      - sh
      - -c
      - |
        # Crea solo le directory necessarie (senza chown/chmod)
        mkdir -p /var/www/html/storage/app/public
        mkdir -p /var/www/html/storage/framework/cache/data
        mkdir -p /var/www/html/storage/framework/sessions
        mkdir -p /var/www/html/storage/framework/views
        mkdir -p /var/www/html/storage/logs
        mkdir -p /var/www/html/storage/uploads
        mkdir -p /var/www/html/storage/configurations
        mkdir -p /var/www/html/storage/conversion-routines
        mkdir -p /var/www/html/storage/submission-routines
        mkdir -p /var/www/html/storage/jobs
    volumeMounts:
    - name: importer-storage
      mountPath: /var/www/html/storage
  
  containers:
  - name: firefly-importer
    image: docker.io/fireflyiii/data-importer:latest
    securityContext:
      runAsUser: 0  # Nginx richiede root
    ports:
    - name: importer-http
      containerPort: 8080
    env:
    - name: FIREFLY_III_URL
      value: "http://firefly-pod:8080"
    - name: VANITY_URL
      value: "https://finanza.simonemiglio.eu"
    - name: VERIFY_TLS_SECURITY
      value: "false"
    - name: TZ
      value: "Europe/Rome"
    - name: TRUSTED_PROXIES
      value: "**"
    - name: EXPECT_SECURE_URL
      value: "false"
    - name: LOG_LEVEL
      value: "debug"
    volumeMounts:
    - name: php-fpm-conf
      mountPath: /usr/local/etc/php-fpm.d/www.conf
    - name: importer-storage
      mountPath: /var/www/html/storage
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        memory: "256Mi"
  
  volumes:
  - name: php-fpm-conf
    hostPath:
      path: /home/osvaldo/podman/data/firefly-importer/www.conf
      type: File
  - name: importer-storage
    hostPath:
      path: /home/osvaldo/podman/data/firefly-importer/storage
      type: DirectoryOrCreate
