apiVersion: v1
kind: Pod
metadata:
  name: homepage-pod
  labels:
    app: homepage
    io.containers.autoupdate: "image"
spec:
  automountServiceAccountToken: false
  containers:
  - name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
    - name: http
      containerPort: 3000
    env:
    - name: HOMEPAGE_ALLOWED_HOSTS
      value: "home.simonemiglio.eu"
    - name: HOST
      value: "0.0.0.0"
    - name: HOSTNAME
      value: "0.0.0.0"
    volumeMounts:
    - name: homepage-config-volume
      mountPath: /app/config
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
        ephemeral-storage: "1Gi"
      limits:
        memory: "256Mi"
        ephemeral-storage: "2Gi"
  volumes:
  - name: homepage-config-volume
    hostPath:
      path: /home/osvaldo/podman/data/homepage/config
      type: DirectoryOrCreate
