apiVersion: v1
kind: Pod
metadata:
  name: immich-server
  labels:
    app: immich
    io.containers.autoupdate: "image"
spec:
  automountServiceAccountToken: false
  containers:
    # --- Immich Server Application ---
  - name: immich-app-server
    image: ghcr.io/immich-app/immich-server:release
    ports:
    - name: http-immich
      containerPort: 2283
      hostPort: 2283
    env:
    - name: DB_HOSTNAME
      value: "127.0.0.1"
    - name: REDIS_HOSTNAME
      value: "127.0.0.1"
    - name: IMMICH_VERSION
      value: "release"
    - name: NODE_ENV
      value: "production"
    - name: IMMICH_API_METRICS_PORT
      value: "3001" 
    # --- DB Secrets ---
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: immich-db-user-k8s
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: immich-db-password-k8s
          key: password
    - name: DB_DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: immich-db-name-k8s
          key: dbname
    # --- Network Configuration (IPv4 Force) ---
    - name: IMMICH_HOST
      value: "0.0.0.0"
    - name: IMMICH_PORT
      value: "2283"
    - name: HOST
      value: "0.0.0.0"
    - name: IMMICH_MACHINE_LEARNING_URL
      value: "http://127.0.0.1:3003"
    - name: IMMICH_LOG_LEVEL
      value: "debug"
    volumeMounts:
    - name: immich-uploads-volume
      mountPath: /data
    - name: host-localtime-volume
      mountPath: /etc/localtime
      readOnly: true
#    resources: { requests: { cpu: "200m", memory: "512Mi" }, limits: { memory: "2Gi" } }

    # --- Immich Machine Learning ---
  - name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    env:
    - name: DB_HOSTNAME
      value: "127.0.0.1"
    - name: REDIS_HOSTNAME
      value: "127.0.0.1"
    - name: IMMICH_VERSION
      value: "release"
    - name: NODE_ENV
      value: "production"
    # --- Force IPv4 Binding Here ---
    - name: MACHINE_LEARNING_HOST
      value: "0.0.0.0"
    - name: IMMICH_HOST  # Critical for some ML versions
      value: "0.0.0.0"
    - name: HOST         # Fallback for Uvicorn
      value: "0.0.0.0"
    - name: MACHINE_LEARNING_PORT
      value: "3003"
    - name: DB_USERNAME
      valueFrom: { secretKeyRef: { name: immich-db-user-k8s, key: username } }
    - name: DB_PASSWORD
      valueFrom: { secretKeyRef: { name: immich-db-password-k8s, key: password } }
    - name: DB_DATABASE_NAME
      valueFrom: { secretKeyRef: { name: immich-db-name-k8s, key: dbname } }
    volumeMounts:
    - name: immich-model-cache-volume
      mountPath: /cache
#    resources: { requests: { cpu: "200m", memory: "512Mi" }, limits: { memory: "4Gi" } }

    # --- Valkey (Redis) ---
  - name: immich-valkey
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    ports:
    - name: valkey-port
      containerPort: 6379
    resources: { requests: { cpu: "100m", memory: "128Mi" }, limits: { memory: "512Mi" } }

    # --- PostgreSQL Database ---
  - name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    ports:
    - name: postgres-port
      containerPort: 5432
    env:
    - name: POSTGRES_USER
      valueFrom: { secretKeyRef: { name: immich-db-user-k8s, key: username } }
    - name: POSTGRES_PASSWORD
      valueFrom: { secretKeyRef: { name: immich-db-password-k8s, key: password } }
    - name: POSTGRES_DB
      valueFrom: { secretKeyRef: { name: immich-db-name-k8s, key: dbname } }
    - name: POSTGRES_INITDB_ARGS
      value: "--data-checksums"
    volumeMounts:
    - name: immich-db-data-volume
      mountPath: /var/lib/postgresql/data
    resources: { requests: { cpu: "100m", memory: "256Mi" }, limits: { memory: "1Gi" } }

  volumes:
  - name: immich-uploads-volume
    hostPath:
      path: /mnt/immich_storage
      type: Directory
  - name: immich-db-data-volume
    hostPath:
      path: /mnt/HC_Volume_103834258/podman-data/immich/immich_db
      type: Directory
  - name: immich-model-cache-volume
    hostPath:
      path: /home/osvaldo/podman/data/immich/immich_model_cache
      type: DirectoryOrCreate
  - name: host-localtime-volume
    hostPath:
      path: /etc/localtime
      type: File
