apiVersion: v1
kind: Pod
metadata:
  name: portainer-pod
spec:
  containers:
  - name: portainer
    image: docker.io/portainer/portainer-ce:lts
    ports:
    - containerPort: 9443
      hostPort: 9443
    - containerPort: 9000
      hostPort: 9000
    - containerPort: 8000
      hostPort: 8000
    volumeMounts:
    - name: portainer-data
      mountPath: /data
    - name: podman-socket
      mountPath: /var/run/docker.sock
    securityContext:
      privileged: true
      runAsUser: 0
      seLinuxOptions:
        type: spc_t
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 100m
  volumes:
  - name: portainer-data
    hostPath:
      path: /home/osvaldo/podman/data/portainer/data
      type: DirectoryOrCreate
  - name: podman-socket
    hostPath:
      path: /run/user/1000/podman/podman.sock
      type: Socket
  restartPolicy: Always
